export const visitAsideLinks = [
    {text:'Tickets', href:'/visit/tickets'},
    {text:'Frequently Asked Questions', href:'/'},
    {text:'Calendar', href:'/'},
    {text:'Hours', href:'/'},
    {text:'Getting Here', href:'/'},
    {text:'Museum Map', href:'/'},
    {text:'Reduced Rates & Community Day', href:'/'},
    {text:'Accessibility', href:'/'},
    {text:'Tips for Visiting with Kids', href:'/'},
    {text:'Exhibits', href:'/'},
    {text:'Tactile Dome', href:'/'},
    {text:'Artworks on View', href:'/'},
    {text:'Cinema Arts', href:'/'},
    {text:'Kanbar Forum', href:'/'},
    {text:'Black Box', href:'/'},
    {text:'Museum Galleries', href:'/'},
    {text:'Restaurant & Café', href:'/'},
    {text:'School Field Trips', href:'/'},
    {text:'Groups / Tour Operators', href:'/'},
    {text:'Event Rentals', href:'/'},
    {text:'Exploratorium Store', href:'/'},
    {text:'Contact Us', href:'/'},
    {text:'Español', href:'/'},
    {text:'繁體中文', href:'/'},
    {text:'简体中文', href:'/'},
    {text:'한국어', href:'/'},
    {text:'Français', href:'/'},
    {text:'Deutsch', href:'/'},
    {text:'Português', href:'/'},
    {text:'日本語', href:'/'},
]